version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: pipectl
    main: ./cmd/pipectl
    binary: pipectl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: pipectl
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

nfpms:
  - id: pipectl-linux-packages
    package_name: pipectl
    vendor: pipectl
    homepage: https://github.com/pipectl/pipectl
    maintainer: Shane Bell
    description: Run YAML-defined data pipelines from the command line.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    file_name_template: "{{ .PackageName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

homebrew_casks:
  - repository:
      owner: pipectl
      name: homebrew-pipectl
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    homepage: https://github.com/pipectl/pipectl
    description: Run YAML-defined data pipelines from the command line.
    binaries:
      - pipectl
    hooks:
      post:
        install: 'system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pipectl"]'

dockers:
  - image_templates:
      - "ghcr.io/pipectl/pipectl:{{ .Tag }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"

  - image_templates:
      - "ghcr.io/pipectl/pipectl:{{ .Tag }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/pipectl/pipectl:{{ .Tag }}"
    image_templates:
      - "ghcr.io/pipectl/pipectl:{{ .Tag }}-amd64"
      - "ghcr.io/pipectl/pipectl:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/pipectl/pipectl:latest"
    image_templates:
      - "ghcr.io/pipectl/pipectl:{{ .Tag }}-amd64"
      - "ghcr.io/pipectl/pipectl:{{ .Tag }}-arm64"

scoops:
  - repository:
      owner: pipectl
      name: scoop-pipectl
      token: "{{ .Env.SCOOP_BUCKET_TOKEN }}"
    homepage: https://github.com/pipectl/pipectl
    description: Run YAML-defined data pipelines from the command line.
    license: MIT
